# Site
name: "Matheus Fidelis"
title: "Matheus Fidelis - Engineering Blog"
description: "Technical Blog"
logo: 'assets/images/logo.png'
favicon: 'assets/images/logo.png'
baseurl: ""
google_analytics: 'UA-46278016-1'
include: ["_pages"]
permalink: /:title/

url: "https://fidelissauro.dev"

# Authors
authors:
  matheus:
    name: Matheus Fidelis
    display_name: Matheus Fidelis
    gravatar: 5700ede08434f0ab49b75fe5543f129b
    email: matheus@nanoshots.com.br
    web: https://msfidelis.github.io/
    twitter: https://bsky.app/profile/fidelissauro.bsky.social
    description: "Principal Engineer, Lifelong Learner, Site Reliability Engineer, Cloud and Containers Wizard, Software Alchemist and Home Bartender"

# Plugins
plugins:
  - jekyll-paginate
  - jekyll-sitemap
  - jekyll-feed
  - jekyll-seo-tag
  - jekyll-archives
  - jekyll-gist
  - jekyll-embed-urls
  - jekyll-linkpreview
  # - jekyll-compress-images

whitelist:
  - jekyll-paginate
  - jekyll-sitemap
  - jekyll-feed
  - jekyll-seo-tag
  - jekyll-archives
  - jekyll-gist
  - jekyll-embed-urls
  - jekyll-linkpreview
  # - jekyll-compress-images

# compress_images:
#   images_path: "assets/images/**/*.{gif,png,jpg,jpeg,svg}"

# Archives
jekyll-archives:
  enabled:
    - categories
  layout: archive
  permalinks:
    category: '/category/:name/'
    
# Pagination 
paginate: 9
paginate_path: /page:num/
    
# Other
markdown: kramdown

kramdown:
  input: GFM
  syntax_highlighter: rouge
  syntax_highlighter_opts:
    block:
      line_numbers: true

# Adsense (change to "enabled" to activate, also your client id and ad slot. Create a new ad unit from your Adsense account to get the slot.)
# adsense: "disabled"
# adsense-data-ad-client: "ca-pub-3412143450191416"
# adsense-data-ad-slot: "1363087678"

# Lazy Images ("enabled" or "disabled")
lazyimages: "enabled"

exclude: [changelog.md, LICENSE.txt, README.md, Gemfile, Gemfile.lock, docker-compose.yml]

embed:
# Extra elements to remove
  scrub:
  - form
  - input
  - textarea
  - button
  - fieldset
  - select
  - option
  - optgroup
  - canvas
  - area
  - map
