%%{init: {'theme':'neutral'}}%%
sequenceDiagram
    participant Cliente
    participant ServerOrquestrador as Orquestrador
    participant BackendA as Aplicação 01
    participant BackendB as Aplicação 02

    Cliente->>ServerOrquestrador: Inicia Transação (2PC)
    note right of Cliente: Requisição síncrona

    ServerOrquestrador->>BackendA: Fase 1 - Prepare
    BackendA-->>ServerOrquestrador: OK
    
    ServerOrquestrador->>BackendB: Fase 1 - Prepare
    BackendB-->>ServerOrquestrador: OK 

    alt Todos OK
        ServerOrquestrador->>BackendA: Fase 2 - COMMIT
        BackendA-->>ServerOrquestrador: COMMIT_OK
        
        ServerOrquestrador->>BackendB: Fase 2 - COMMIT
        BackendB-->>ServerOrquestrador: COMMIT_OK

        ServerOrquestrador-->>Cliente: Transação Concluída (Sucesso)
    end
